import type { Metadata } from 'next'
import Navbar from "./components/Navbar";
import { Toaster } from 'react-hot-toast';
import VerifyEmailNavbar from "./components/VerifyEmailNavbar";
import { AuthProvider } from '../context/AuthContext';

// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_TITLE || 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProvider>
          <div className="min-h-screen">
            <VerifyEmailNavbar />
            <Navbar />
            {children}
            <Toaster position="top-right" />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}