import type { Metadata } from 'next'
import Navbar from "./components/Navbar";
import { Toaster } from 'react-hot-toast';

// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body>
        <Navbar />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  )
}